require "reso/version"
require "reso/railtie" if defined?(Rails)
require "reso/config/inflections.rb"
require "reso/app/models/application_record.rb"
require "reso/app/models/reso/enumeration.rb"
require "reso/app/models/reso/parent_child_assignment.rb"

require "reso/app/models/reso/above_grade_finished_area_source_assignment.rb"
require "reso/app/models/reso/above_grade_finished_area_units_assignment.rb"
require "reso/app/models/reso/accessibility_feature.rb"
require "reso/app/models/reso/accessibility_feature_assignment.rb"
require "reso/app/models/reso/actor_type.rb"
require "reso/app/models/reso/actor_type_assignment.rb"
require "reso/app/models/reso/appliance.rb"
require "reso/app/models/reso/appliance_assignment.rb"
require "reso/app/models/reso/architectural_style.rb"
require "reso/app/models/reso/architectural_style_assignment.rb"
require "reso/app/models/reso/area_source.rb"
require "reso/app/models/reso/area_source_assignment.rb"
require "reso/app/models/reso/area_units.rb"
require "reso/app/models/reso/area_units_assignment.rb"
require "reso/app/models/reso/association_amenities_assignment.rb"
require "reso/app/models/reso/association_amenity.rb"
require "reso/app/models/reso/association_fee_includes.rb"
require "reso/app/models/reso/association_fee_includes_assignment.rb"
require "reso/app/models/reso/attended.rb"
require "reso/app/models/reso/attended_assignment.rb"
require "reso/app/models/reso/basement.rb"
require "reso/app/models/reso/basement_assignment.rb"
require "reso/app/models/reso/below_grade_finished_area_source_assignment.rb"
require "reso/app/models/reso/below_grade_finished_area_units_assignment.rb"
require "reso/app/models/reso/body_type.rb"
require "reso/app/models/reso/body_type_assignment.rb"
require "reso/app/models/reso/building_area_source_assignment.rb"
require "reso/app/models/reso/building_features.rb"
require "reso/app/models/reso/building_features_assignment.rb"
require "reso/app/models/reso/business_type.rb"
require "reso/app/models/reso/business_type_assignment.rb"
require "reso/app/models/reso/buyer_agent_designation.rb"
require "reso/app/models/reso/buyer_agent_designation_assignment.rb"
require "reso/app/models/reso/buyer_financing.rb"
require "reso/app/models/reso/buyer_financing_assignment.rb"
require "reso/app/models/reso/change_type.rb"
require "reso/app/models/reso/change_type_assignment.rb"
require "reso/app/models/reso/city.rb"
require "reso/app/models/reso/city_assignment.rb"
require "reso/app/models/reso/class_name.rb"
require "reso/app/models/reso/class_name_assignment.rb"
require "reso/app/models/reso/co_buyer_agent_designation.rb"
require "reso/app/models/reso/co_buyer_agent_designation_assignment.rb"
require "reso/app/models/reso/co_list_agent_designation.rb"
require "reso/app/models/reso/co_list_agent_designation_assignment.rb"
require "reso/app/models/reso/common_interest.rb"
require "reso/app/models/reso/common_interest_assignment.rb"
require "reso/app/models/reso/common_walls.rb"
require "reso/app/models/reso/common_walls_assignment.rb"
require "reso/app/models/reso/community_feature.rb"
require "reso/app/models/reso/community_feature_assignment.rb"
require "reso/app/models/reso/compensation_type.rb"
require "reso/app/models/reso/compensation_type_assignment.rb"
require "reso/app/models/reso/concessions.rb"
require "reso/app/models/reso/concessions_assignment.rb"
require "reso/app/models/reso/construction_material.rb"
require "reso/app/models/reso/construction_materials_assignment.rb"
require "reso/app/models/reso/contact_listing_preference.rb"
require "reso/app/models/reso/contact_listing_preference_assignment.rb"
require "reso/app/models/reso/contact_status.rb"
require "reso/app/models/reso/contact_status_assignment.rb"
require "reso/app/models/reso/contact_type.rb"
require "reso/app/models/reso/contact_type_assignment.rb"
require "reso/app/models/reso/cooling.rb"
require "reso/app/models/reso/cooling_assignment.rb"
require "reso/app/models/reso/country.rb"
require "reso/app/models/reso/country_assignment.rb"
require "reso/app/models/reso/county_or_parish.rb"
require "reso/app/models/reso/county_or_parish_assignment.rb"
require "reso/app/models/reso/current_financing.rb"
require "reso/app/models/reso/current_financing_assignment.rb"
require "reso/app/models/reso/current_use.rb"
require "reso/app/models/reso/current_use_assignment.rb"
require "reso/app/models/reso/daily_schedule.rb"
require "reso/app/models/reso/daily_schedule_assignment.rb"
require "reso/app/models/reso/development_status.rb"
require "reso/app/models/reso/development_status_assignment.rb"
require "reso/app/models/reso/device_type.rb"
require "reso/app/models/reso/device_type_assignment.rb"
require "reso/app/models/reso/direction_faces.rb"
require "reso/app/models/reso/direction_faces_assignment.rb"
require "reso/app/models/reso/door_feature.rb"
require "reso/app/models/reso/door_features_assignment.rb"
require "reso/app/models/reso/electric.rb"
require "reso/app/models/reso/electric_assignment.rb"
require "reso/app/models/reso/elementary_school.rb"
require "reso/app/models/reso/elementary_school_assignment.rb"
require "reso/app/models/reso/elementary_school_district.rb"
require "reso/app/models/reso/elementary_school_district_assignment.rb"
require "reso/app/models/reso/elevation_unit.rb"
require "reso/app/models/reso/elevation_unit_assignment.rb"
require "reso/app/models/reso/enumeration.rb"
require "reso/app/models/reso/event_target.rb"
require "reso/app/models/reso/event_target_assignment.rb"
require "reso/app/models/reso/event_type.rb"
require "reso/app/models/reso/event_type_assignment.rb"
require "reso/app/models/reso/existing_lease_type.rb"
require "reso/app/models/reso/existing_lease_type_assignment.rb"
require "reso/app/models/reso/exterior_feature.rb"
require "reso/app/models/reso/exterior_features_assignment.rb"
require "reso/app/models/reso/farm_land_area_source.rb"
require "reso/app/models/reso/farm_land_area_source_assignment.rb"
require "reso/app/models/reso/farm_land_area_unit.rb"
require "reso/app/models/reso/farm_land_area_unit_assignment.rb"
require "reso/app/models/reso/fee_frequency.rb"
require "reso/app/models/reso/fee_frequency_assignment.rb"
require "reso/app/models/reso/fencing.rb"
require "reso/app/models/reso/fencing_assignment.rb"
require "reso/app/models/reso/financial_data_source.rb"
require "reso/app/models/reso/financial_data_source_assignment.rb"
require "reso/app/models/reso/fireplace_feature.rb"
require "reso/app/models/reso/fireplace_feature_assignment.rb"
require "reso/app/models/reso/flooring.rb"
require "reso/app/models/reso/flooring_assignment.rb"
require "reso/app/models/reso/foundation_detail.rb"
require "reso/app/models/reso/foundation_details_assignment.rb"
require "reso/app/models/reso/frontage_type.rb"
require "reso/app/models/reso/frontage_type_assignment.rb"
require "reso/app/models/reso/furnished.rb"
require "reso/app/models/reso/furnished_assignment.rb"
require "reso/app/models/reso/green_building_verification_type.rb"
require "reso/app/models/reso/green_building_verification_type_assignment.rb"
require "reso/app/models/reso/green_energy_efficient.rb"
require "reso/app/models/reso/green_energy_efficient_assignment.rb"
require "reso/app/models/reso/green_energy_generation.rb"
require "reso/app/models/reso/green_energy_generation_assignment.rb"
require "reso/app/models/reso/green_indoor_air_quality.rb"
require "reso/app/models/reso/green_indoor_air_quality_assignment.rb"
require "reso/app/models/reso/green_sustainability.rb"
require "reso/app/models/reso/green_sustainability_assignment.rb"
require "reso/app/models/reso/green_verification_source.rb"
require "reso/app/models/reso/green_verification_source_assignment.rb"
require "reso/app/models/reso/green_verification_status.rb"
require "reso/app/models/reso/green_verification_status_assignment.rb"
require "reso/app/models/reso/green_water_conservation.rb"
require "reso/app/models/reso/green_water_conservation_assignment.rb"
require "reso/app/models/reso/heating.rb"
require "reso/app/models/reso/heating_assignment.rb"
require "reso/app/models/reso/high_school.rb"
require "reso/app/models/reso/high_school_assignment.rb"
require "reso/app/models/reso/high_school_district.rb"
require "reso/app/models/reso/high_school_district_assignment.rb"
require "reso/app/models/reso/horse_amenity.rb"
require "reso/app/models/reso/horse_amenity_assignment.rb"
require "reso/app/models/reso/hours_days_of_operation.rb"
require "reso/app/models/reso/hours_days_of_operation_assignment.rb"
require "reso/app/models/reso/image_of.rb"
require "reso/app/models/reso/image_of_assignment.rb"
require "reso/app/models/reso/income_includes.rb"
require "reso/app/models/reso/income_includes_assignment.rb"
require "reso/app/models/reso/interior_or_room_feature.rb"
require "reso/app/models/reso/interior_or_room_feature_assignment.rb"
require "reso/app/models/reso/labor_information.rb"
require "reso/app/models/reso/labor_information_assignment.rb"
require "reso/app/models/reso/land_lease_amount_frequency_assignment.rb"
require "reso/app/models/reso/languages.rb"
require "reso/app/models/reso/languages_assignment.rb"
require "reso/app/models/reso/laundry_feature.rb"
require "reso/app/models/reso/laundry_feature_assignment.rb"
require "reso/app/models/reso/lease_renewal_compensation.rb"
require "reso/app/models/reso/lease_renewal_compensation_assignment.rb"
require "reso/app/models/reso/lease_term.rb"
require "reso/app/models/reso/lease_term_assignment.rb"
require "reso/app/models/reso/levels.rb"
require "reso/app/models/reso/levels_assignment.rb"
require "reso/app/models/reso/linear_units.rb"
require "reso/app/models/reso/linear_units_assignment.rb"
require "reso/app/models/reso/list_agent_designation.rb"
require "reso/app/models/reso/list_agent_designation_assignment.rb"
require "reso/app/models/reso/listing_agreement.rb"
require "reso/app/models/reso/listing_agreement_assignment.rb"
require "reso/app/models/reso/listing_association.rb"
require "reso/app/models/reso/listing_association_assignment.rb"
require "reso/app/models/reso/listing_service.rb"
require "reso/app/models/reso/listing_service_assignment.rb"
require "reso/app/models/reso/listing_terms.rb"
require "reso/app/models/reso/listing_terms_assignment.rb"
require "reso/app/models/reso/living_area_source_assignment.rb"
require "reso/app/models/reso/lock_box_type.rb"
require "reso/app/models/reso/lock_box_type_assignment.rb"
require "reso/app/models/reso/lot_dimensions_source.rb"
require "reso/app/models/reso/lot_dimensions_source_assignment.rb"
require "reso/app/models/reso/lot_feature.rb"
require "reso/app/models/reso/lot_feature_assignment.rb"
require "reso/app/models/reso/lot_size_source.rb"
require "reso/app/models/reso/lot_size_source_assignment.rb"
require "reso/app/models/reso/lot_size_unit.rb"
require "reso/app/models/reso/lot_size_unit_assignment.rb"
require "reso/app/models/reso/media_category.rb"
require "reso/app/models/reso/media_category_assignment.rb"
require "reso/app/models/reso/media_type.rb"
require "reso/app/models/reso/media_type_assignment.rb"
require "reso/app/models/reso/member_designation.rb"
require "reso/app/models/reso/member_designation_assignment.rb"
require "reso/app/models/reso/member_other_phone_type.rb"
require "reso/app/models/reso/member_other_phone_type_assignment.rb"
require "reso/app/models/reso/member_status.rb"
require "reso/app/models/reso/member_status_assignment.rb"
require "reso/app/models/reso/member_type.rb"
require "reso/app/models/reso/member_type_assignment.rb"
require "reso/app/models/reso/middle_or_junior_school.rb"
require "reso/app/models/reso/middle_or_junior_school_assignment.rb"
require "reso/app/models/reso/middle_or_junior_school_district.rb"
require "reso/app/models/reso/middle_or_junior_school_district_assignment.rb"
require "reso/app/models/reso/mls_area_major.rb"
require "reso/app/models/reso/mls_area_major_assignment.rb"
require "reso/app/models/reso/mls_area_minor.rb"
require "reso/app/models/reso/mls_area_minor_assignment.rb"
require "reso/app/models/reso/mls_status.rb"
require "reso/app/models/reso/mls_status_assignment.rb"
require "reso/app/models/reso/mobile_dim_units_assignment.rb"
require "reso/app/models/reso/noted_by.rb"
require "reso/app/models/reso/noted_by_assignment.rb"
require "reso/app/models/reso/object_id_type.rb"
require "reso/app/models/reso/object_id_type_assignment.rb"
require "reso/app/models/reso/object_type.rb"
require "reso/app/models/reso/object_type_assignment.rb"
require "reso/app/models/reso/occupant_type.rb"
require "reso/app/models/reso/occupant_type_assignment.rb"
require "reso/app/models/reso/office_branch_type.rb"
require "reso/app/models/reso/office_branch_type_assignment.rb"
require "reso/app/models/reso/office_status.rb"
require "reso/app/models/reso/office_status_assignment.rb"
require "reso/app/models/reso/office_type.rb"
require "reso/app/models/reso/office_type_assignment.rb"
require "reso/app/models/reso/open_house_status.rb"
require "reso/app/models/reso/open_house_status_assignment.rb"
require "reso/app/models/reso/open_house_type.rb"
require "reso/app/models/reso/open_house_type_assignment.rb"
require "reso/app/models/reso/operating_expense_includes.rb"
require "reso/app/models/reso/operating_expense_includes_assignment.rb"
require "reso/app/models/reso/other_equipment.rb"
require "reso/app/models/reso/other_equipment_assignment.rb"
require "reso/app/models/reso/other_phone_type.rb"
require "reso/app/models/reso/other_phone_type_assignment.rb"
require "reso/app/models/reso/other_structure.rb"
require "reso/app/models/reso/other_structure_assignment.rb"
require "reso/app/models/reso/owner_pays.rb"
require "reso/app/models/reso/owner_pays_assignment.rb"
require "reso/app/models/reso/ownership_type.rb"
require "reso/app/models/reso/ownership_type_assignment.rb"
require "reso/app/models/reso/parking_feature.rb"
require "reso/app/models/reso/parking_feature_assignment.rb"
require "reso/app/models/reso/patio_and_porch_feature.rb"
require "reso/app/models/reso/patio_and_porch_feature_assignment.rb"
require "reso/app/models/reso/permission.rb"
require "reso/app/models/reso/permission_assignment.rb"
require "reso/app/models/reso/pets_allowed.rb"
require "reso/app/models/reso/pets_allowed_assignment.rb"
require "reso/app/models/reso/pool_feature.rb"
require "reso/app/models/reso/pool_feature_assignment.rb"
require "reso/app/models/reso/possession.rb"
require "reso/app/models/reso/possession_assignment.rb"
require "reso/app/models/reso/possible_use.rb"
require "reso/app/models/reso/possible_use_assignment.rb"
require "reso/app/models/reso/postal_city.rb"
require "reso/app/models/reso/postal_city_assignment.rb"
require "reso/app/models/reso/power_production_annual_status.rb"
require "reso/app/models/reso/power_production_annual_status_assignment.rb"
require "reso/app/models/reso/power_production_type.rb"
require "reso/app/models/reso/power_production_type_assignment.rb"
require "reso/app/models/reso/preferred_address.rb"
require "reso/app/models/reso/preferred_address_assignment.rb"
require "reso/app/models/reso/preferred_phone.rb"
require "reso/app/models/reso/preferred_phone_assignment.rb"
require "reso/app/models/reso/property.rb"
require "reso/app/models/reso/property_condition.rb"
require "reso/app/models/reso/property_condition_assignment.rb"
require "reso/app/models/reso/property_sub_type.rb"
require "reso/app/models/reso/property_sub_type_assignment.rb"
require "reso/app/models/reso/property_type.rb"
require "reso/app/models/reso/property_type_assignment.rb"
require "reso/app/models/reso/queue_transaction_type.rb"
require "reso/app/models/reso/queue_transaction_type_assignment.rb"
require "reso/app/models/reso/reason_active_or_disabled.rb"
require "reso/app/models/reso/reason_active_or_disabled_assignment.rb"
require "reso/app/models/reso/rent_includes.rb"
require "reso/app/models/reso/rent_includes_assignment.rb"
require "reso/app/models/reso/resource_name.rb"
require "reso/app/models/reso/resource_name_assignment.rb"
require "reso/app/models/reso/road_frontage_type.rb"
require "reso/app/models/reso/road_frontage_type_assignment.rb"
require "reso/app/models/reso/road_responsibility.rb"
require "reso/app/models/reso/road_responsibility_assignment.rb"
require "reso/app/models/reso/road_surface_type.rb"
require "reso/app/models/reso/road_surface_type_assignment.rb"
require "reso/app/models/reso/roof.rb"
require "reso/app/models/reso/roof_assignment.rb"
require "reso/app/models/reso/room_type.rb"
require "reso/app/models/reso/room_type_assignment.rb"
require "reso/app/models/reso/rule_format.rb"
require "reso/app/models/reso/rule_format_assignment.rb"
require "reso/app/models/reso/schedule_type.rb"
require "reso/app/models/reso/schedule_type_assignment.rb"
require "reso/app/models/reso/search_query_type.rb"
require "reso/app/models/reso/search_query_type_assignment.rb"
require "reso/app/models/reso/security_feature.rb"
require "reso/app/models/reso/security_feature_assignment.rb"
require "reso/app/models/reso/sewer.rb"
require "reso/app/models/reso/sewer_assignment.rb"
require "reso/app/models/reso/showing_contact_type.rb"
require "reso/app/models/reso/showing_contact_type_assignment.rb"
require "reso/app/models/reso/showing_requirement.rb"
require "reso/app/models/reso/showing_requirements_assignment.rb"
require "reso/app/models/reso/skirt.rb"
require "reso/app/models/reso/skirt_assignment.rb"
require "reso/app/models/reso/social_media_type.rb"
require "reso/app/models/reso/social_media_type_assignment.rb"
require "reso/app/models/reso/spa_feature.rb"
require "reso/app/models/reso/spa_feature_assignment.rb"
require "reso/app/models/reso/special_license.rb"
require "reso/app/models/reso/special_licenses_assignment.rb"
require "reso/app/models/reso/special_listing_condition.rb"
require "reso/app/models/reso/special_listing_conditions_assignment.rb"
require "reso/app/models/reso/standard_status.rb"
require "reso/app/models/reso/standard_status_assignment.rb"
require "reso/app/models/reso/state_or_province.rb"
require "reso/app/models/reso/state_or_province_assignment.rb"
require "reso/app/models/reso/street_dir_prefix.rb"
require "reso/app/models/reso/street_dir_prefix_assignment.rb"
require "reso/app/models/reso/street_dir_suffix.rb"
require "reso/app/models/reso/street_dir_suffix_assignment.rb"
require "reso/app/models/reso/street_direction.rb"
require "reso/app/models/reso/street_direction_assignment.rb"
require "reso/app/models/reso/street_suffix.rb"
require "reso/app/models/reso/street_suffix_assignment.rb"
require "reso/app/models/reso/structure_type.rb"
require "reso/app/models/reso/structure_type_assignment.rb"
require "reso/app/models/reso/syndicate_to.rb"
require "reso/app/models/reso/syndicate_to_assignment.rb"
require "reso/app/models/reso/tax_status_current.rb"
require "reso/app/models/reso/tax_status_current_assignment.rb"
require "reso/app/models/reso/team_member_type.rb"
require "reso/app/models/reso/team_member_type_assignment.rb"
require "reso/app/models/reso/team_status.rb"
require "reso/app/models/reso/team_status_assignment.rb"
require "reso/app/models/reso/tenant_pays.rb"
require "reso/app/models/reso/tenant_pays_assignment.rb"
require "reso/app/models/reso/unit_type_type.rb"
require "reso/app/models/reso/unit_type_type_assignment.rb"
require "reso/app/models/reso/units_furnished.rb"
require "reso/app/models/reso/units_furnished_assignment.rb"
require "reso/app/models/reso/utilities.rb"
require "reso/app/models/reso/utilities_assignment.rb"
require "reso/app/models/reso/vegetation.rb"
require "reso/app/models/reso/vegetation_assignment.rb"
require "reso/app/models/reso/view.rb"
require "reso/app/models/reso/view_assignment.rb"
require "reso/app/models/reso/water_source.rb"
require "reso/app/models/reso/water_source_assignment.rb"
require "reso/app/models/reso/waterfront_feature.rb"
require "reso/app/models/reso/waterfront_feature_assignment.rb"
require "reso/app/models/reso/window_feature.rb"
require "reso/app/models/reso/window_features_assignment.rb"
require "reso/app/models/reso/year_built_source.rb"
require "reso/app/models/reso/year_built_source_assignment.rb"

require "reso/app/models/reso/property/characteristics.rb"
require "reso/app/models/reso/property/equipment.rb"
require "reso/app/models/reso/property/farming.rb"
require "reso/app/models/reso/property/financial.rb"
require "reso/app/models/reso/property/listing.rb"
require "reso/app/models/reso/property/location.rb"
require "reso/app/models/reso/property/occupant_owner.rb"
require "reso/app/models/reso/property/structure.rb"

require "reso/app/models/reso/property/listing/price.rb"
require "reso/app/models/reso/property/listing/remarks.rb"
require "reso/app/models/reso/property/listing/showing.rb"

require "reso/app/models/reso/property/location/address.rb"
require "reso/app/models/reso/property/location/area.rb"
require "reso/app/models/reso/property/location/gis.rb"
require "reso/app/models/reso/property/location/school.rb"

# require "reso/app/models/reso/accessibility_feature.rb"
# require "reso/app/models/reso/actor_type.rb"
# require "reso/app/models/reso/appliance.rb"
# require "reso/app/models/reso/area_source.rb"
# require "reso/app/models/reso/area_unit.rb"
# require "reso/app/models/reso/association_amenity.rb"
# require "reso/app/models/reso/association_fee_include.rb"
# require "reso/app/models/reso/attended.rb"
# require "reso/app/models/reso/basement.rb"
# require "reso/app/models/reso/body_type.rb"
# require "reso/app/models/reso/buyer_agent_designation.rb"
# require "reso/app/models/reso/buyer_financing.rb"
# require "reso/app/models/reso/business_type.rb"
# require "reso/app/models/reso/change_type.rb"
# require "reso/app/models/reso/class_name.rb"
# require "reso/app/models/reso/co_buyer_agent_designation.rb"
# require "reso/app/models/reso/co_list_agent_designation.rb"
# require "reso/app/models/reso/common_interest.rb"
# require "reso/app/models/reso/common_wall.rb"
# require "reso/app/models/reso/community_feature.rb"
# require "reso/app/models/reso/compensation_type.rb"
# require "reso/app/models/reso/concession.rb"
# require "reso/app/models/reso/construction_material.rb"
# require "reso/app/models/reso/contact_listing_preference.rb"
# require "reso/app/models/reso/contact_status.rb"
# require "reso/app/models/reso/contact_type.rb"
# require "reso/app/models/reso/cooling.rb"
# require "reso/app/models/reso/current_financing.rb"
# require "reso/app/models/reso/current_use.rb"
# require "reso/app/models/reso/daily_schedule.rb"
# require "reso/app/models/reso/development_status.rb"
# require "reso/app/models/reso/device_type.rb"
# require "reso/app/models/reso/direction_face.rb"
# require "reso/app/models/reso/door_feature.rb"
# require "reso/app/models/reso/electric.rb"
# require "reso/app/models/reso/event_target.rb"
# require "reso/app/models/reso/event_type.rb"
# require "reso/app/models/reso/existing_lease_type.rb"
# require "reso/app/models/reso/exterior_feature.rb"
# require "reso/app/models/reso/fencing.rb"
# require "reso/app/models/reso/financial_data_source.rb"
# require "reso/app/models/reso/fireplace_feature.rb"
# require "reso/app/models/reso/flooring.rb"
# require "reso/app/models/reso/foundation_detail.rb"
# require "reso/app/models/reso/frontage_type.rb"
# require "reso/app/models/reso/furnished.rb"
# require "reso/app/models/reso/green_building_verification_type.rb"
# require "reso/app/models/reso/green_energy_efficient.rb"
# require "reso/app/models/reso/green_energy_generation.rb"
# require "reso/app/models/reso/green_indoor_air_quality.rb"
# require "reso/app/models/reso/green_sustainability.rb"
# require "reso/app/models/reso/green_water_conservation.rb"
# require "reso/app/models/reso/heating.rb"
# require "reso/app/models/reso/horse_amenity.rb"
# require "reso/app/models/reso/hours_days_of_operation.rb"
# require "reso/app/models/reso/image_of.rb"
# require "reso/app/models/reso/income_include.rb"
# require "reso/app/models/reso/labor_information.rb"
# require "reso/app/models/reso/laundry_feature.rb"
# require "reso/app/models/reso/lease_renewal_compensation.rb"
# require "reso/app/models/reso/lease_term.rb"
# require "reso/app/models/reso/list_agent_designation.rb"
# require "reso/app/models/reso/listing_agreement.rb"
# require "reso/app/models/reso/listing_service.rb"
# require "reso/app/models/reso/listing_term.rb"
# require "reso/app/models/reso/lock_box_type.rb"
# require "reso/app/models/reso/lot_dimensions_source.rb"
# require "reso/app/models/reso/lot_feature.rb"
# require "reso/app/models/reso/lot_size_source.rb"
# require "reso/app/models/reso/lot_size_unit.rb"
# require "reso/app/models/reso/media_category.rb"
# require "reso/app/models/reso/media_type.rb"
# require "reso/app/models/reso/member_designation.rb"
# require "reso/app/models/reso/member_other_phone_type.rb"
# require "reso/app/models/reso/member_status.rb"
# require "reso/app/models/reso/member_type.rb"
# require "reso/app/models/reso/noted_by.rb"
# require "reso/app/models/reso/object_id_type.rb"
# require "reso/app/models/reso/object_type.rb"
# require "reso/app/models/reso/occupant_type.rb"
# require "reso/app/models/reso/open_house_status.rb"
# require "reso/app/models/reso/open_house_type.rb"
# require "reso/app/models/reso/operating_expense_include.rb"
# require "reso/app/models/reso/other_equipment.rb"
# require "reso/app/models/reso/other_structure.rb"
# require "reso/app/models/reso/owner_pay.rb"
# require "reso/app/models/reso/ownership_type.rb"
# require "reso/app/models/reso/parking_feature.rb"
# require "reso/app/models/reso/patio_and_porch_feature.rb"
# require "reso/app/models/reso/permission.rb"
# require "reso/app/models/reso/pets_allowed.rb"
# require "reso/app/models/reso/pool_feature.rb"
# require "reso/app/models/reso/possession.rb"
# require "reso/app/models/reso/possible_use.rb"
# require "reso/app/models/reso/property_condition.rb"
# require "reso/app/models/reso/property_sub_type.rb"
# require "reso/app/models/reso/property_type.rb"
# require "reso/app/models/reso/queue_transaction_type.rb"
# require "reso/app/models/reso/reason_active_or_disabled.rb"
# require "reso/app/models/reso/rent_include.rb"
# require "reso/app/models/reso/road_frontage_type.rb"
# require "reso/app/models/reso/road_responsibility.rb"
# require "reso/app/models/reso/road_surface_type.rb"
# require "reso/app/models/reso/roof.rb"
# require "reso/app/models/reso/rule_format.rb"
# require "reso/app/models/reso/schedule_type.rb"
# require "reso/app/models/reso/search_query_type.rb"
# require "reso/app/models/reso/security_feature.rb"
# require "reso/app/models/reso/sewer.rb"
# require "reso/app/models/reso/showing_contact_type.rb"
# require "reso/app/models/reso/showing_requirement.rb"
# require "reso/app/models/reso/skirt.rb"
# require "reso/app/models/reso/spa_feature.rb"
# require "reso/app/models/reso/special_license.rb"
# require "reso/app/models/reso/special_listing_condition.rb"
# require "reso/app/models/reso/standard_status.rb"
# require "reso/app/models/reso/street_direction.rb"
# require "reso/app/models/reso/structure_type.rb"
# require "reso/app/models/reso/syndicate_to.rb"
# require "reso/app/models/reso/tax_status_current.rb"
# require "reso/app/models/reso/team_member_type.rb"
# require "reso/app/models/reso/team_status.rb"
# require "reso/app/models/reso/tenant_pay.rb"
# require "reso/app/models/reso/unit_type_type.rb"
# require "reso/app/models/reso/units_furnished.rb"
# require "reso/app/models/reso/utility.rb"
# require "reso/app/models/reso/vegetation.rb"
# require "reso/app/models/reso/view.rb"
# require "reso/app/models/reso/water_source.rb"
# require "reso/app/models/reso/waterfront_feature.rb"
# require "reso/app/models/reso/window_feature.rb"
# require "reso/app/models/reso/year_built_source.rb"
# 
# require "reso/app/models/reso/property.rb"
# require "reso/app/models/reso/property/business.rb"
# require "reso/app/models/reso/property/characteristic.rb"
# require "reso/app/models/reso/property/equipment.rb"
# require "reso/app/models/reso/property/farming.rb"
# require "reso/app/models/reso/property/financial.rb"
# require "reso/app/models/reso/property/hoa.rb"
# require "reso/app/models/reso/property/listing.rb"
# require "reso/app/models/reso/property/listing/agent_office.rb"
# require "reso/app/models/reso/property/listing/agent_office/buyer_agent.rb"
# require "reso/app/models/reso/property/listing/agent_office/buyer_office.rb"
# require "reso/app/models/reso/property/listing/agent_office/co_buyer_agent.rb"
# require "reso/app/models/reso/property/listing/agent_office/co_buyer_office.rb"
# require "reso/app/models/reso/property/listing/agent_office/co_list_agent.rb"
# require "reso/app/models/reso/property/listing/agent_office/co_list_office.rb"
# require "reso/app/models/reso/property/listing/agent_office/list_agent.rb"
# require "reso/app/models/reso/property/listing/agent_office/list_office.rb"
# require "reso/app/models/reso/property/listing/agent_office/team.rb"
# require "reso/app/models/reso/property/listing/closing.rb"
# require "reso/app/models/reso/property/listing/compensation.rb"
# require "reso/app/models/reso/property/listing/contract.rb"
# require "reso/app/models/reso/property/listing/date.rb"
# require "reso/app/models/reso/property/listing/marketing.rb"
# require "reso/app/models/reso/property/listing/media.rb"
# require "reso/app/models/reso/property/listing/price.rb"
# require "reso/app/models/reso/property/listing/remark.rb"
# require "reso/app/models/reso/property/listing/showing.rb"
# require "reso/app/models/reso/property/location.rb"
# require "reso/app/models/reso/property/location/address.rb"
# require "reso/app/models/reso/property/location/area.rb"
# require "reso/app/models/reso/property/location/gis.rb"
# require "reso/app/models/reso/property/location/school.rb"
# require "reso/app/models/reso/property/occupant_owner.rb"
# require "reso/app/models/reso/property/structure.rb"
# require "reso/app/models/reso/property/structure/performance.rb"
# require "reso/app/models/reso/property/structure/performance/green_marketing.rb"
# require "reso/app/models/reso/property/structure/performance/green_verification.rb"
# require "reso/app/models/reso/property/structure/room.rb"
# require "reso/app/models/reso/property/tax.rb"
# require "reso/app/models/reso/property/unit_type.rb"
# require "reso/app/models/reso/property/utility.rb"
# require "reso/app/models/reso/member.rb"
# require "reso/app/models/reso/office.rb"
# require "reso/app/models/reso/contact.rb"
# require "reso/app/models/reso/contact_listing.rb"
# require "reso/app/models/reso/media.rb"
# require "reso/app/models/reso/history_transactional.rb"
# require "reso/app/models/reso/internet_tracking.rb"
# require "reso/app/models/reso/internet_tracking/actor.rb"
# require "reso/app/models/reso/internet_tracking/event.rb"
# require "reso/app/models/reso/internet_tracking/object.rb"
# require "reso/app/models/reso/saved_search.rb"
# require "reso/app/models/reso/open_house.rb"
# require "reso/app/models/reso/prospecting.rb"
# require "reso/app/models/reso/queue.rb"
# require "reso/app/models/reso/rule.rb"
# require "reso/app/models/reso/showing.rb"
# require "reso/app/models/reso/showing/agent.rb"
# require "reso/app/models/reso/showing/listing.rb"
# require "reso/app/models/reso/team.rb"
# require "reso/app/models/reso/team_member.rb"
# require "reso/app/models/reso/ouid.rb"
# require "reso/app/models/reso/contact_listing_note.rb"
# require "reso/app/models/reso/other_phone.rb"
# require "reso/app/models/reso/property_green_verification.rb"
# require "reso/app/models/reso/property_power_production.rb"
# require "reso/app/models/reso/property_room.rb"
# require "reso/app/models/reso/property_unit_type.rb"
# require "reso/app/models/reso/social_media.rb"

module RESO
  class Error < StandardError; end
  # Your code goes here...
end
